### PR TITLE
add rmarkdown to VignetteBuilder

### PR DESCRIPTION
**Pull request by pawelru**
fix nosuggest ci

### CODE REVIEW

**Review by donyunardi — COMMENTED** [review]
Sorry just got to this. 

I re-ran the Schedule pipeline for r-hub workflow and it still failed because it wants `nestcolor`:
https://github.com/insightsengineering/goshawk/actions/runs/11787673893/job/32833413336

I think we should add `nestcolor` too? Osprey pipeline is failing as well for the same reason.
https://github.com/insightsengineering/osprey/actions/runs/11761956162/job/32764309495

**Comment by pawelru** [comment]
thanks for letting me know - I will push changes soon

**Comment by pawelru** [comment]
noSuggests passed: https://github.com/insightsengineering/goshawk/actions/runs/11797719254/job/32862325239

There are other failures but that would require more thinking what's going on

**Review by donyunardi — APPROVED** [review]
lgtm

**Pull request merged**
