### PR TITLE
159 Implement `nestcolor` in `goshawk`

### LINKED ISSUE #159: Implement nestcolors in the package
Implement nestcolors in the package

### PR DESCRIPTION
**Pull request by edelarua**
Closes #159 

To avoid errors, needs to be merged simultaneously with insightsengineering/nestcolor#20, https://github.com/insightsengineering/teal.goshawk/pull/171, https://github.com/insightsengineering/osprey/pull/92, https://github.com/insightsengineering/teal.osprey/pull/162, and https://github.com/insightsengineering/teal.modules.general/pull/428.

### CODE REVIEW

**Comment by npaszty** [comment]
current implementation for associating line colors to treatment groups is done in the pre-processing using color_manual.
does the nestcolor function enable this type of explicit mapping?

**Comment by edelarua** [comment]
> current implementation for associating line colors to treatment groups is done in the pre-processing using color_manual. does the nestcolor function enable this type of explicit mapping?

Hi @npaszty, `nestcolor` has been implemented in this package and `teal.goshawk` such that the color palette will only be applied when `library(nestcolor)` is run first and `color_manual = NULL`.  Otherwise colors are not changed from the previous setup. Let me know if we should change any of this here or in `teal.goshawk`!

**Comment by npaszty** [comment]
@edelarua 

yes, I saw the conditional processing in the MR. that's not really the question though. I wanted to know if the nestcolor functionality allows explicit mapping of color to treatment groups. as I look at it it just seems like it allows user to create a vector of colors.

**Comment by npaszty** [comment]
okay thanks.

**Pull request merged**
