### PR TITLE
fix vline_vars display

### LINKED ISSUE #230: Horizontal/Vertical Range Lines: Correlation Plot
### What happened?

There is odd behavior between the two range line UI elements.

For our study data we see that LOQFL flag is ste to "Y" for a PARAM where a lower limit of quantitation is observed. The value is "<4". We see the apprpriate value in the footnote and that the LoQ legend is included when selecting the PARAM. 

The PARAM is on the x-axis and we would like to set the vertical range line that would intersect the x-axis at the limit value of 4. when the LLOQN value is selected in the vertical range line element the vertical line is not displayed. it only displays when we also select LLOQN in the horizontal range line UI element

Only vertical range line selected
image

Both vertical and horizontal range line selected
image

Having the horizontal range line section trigger the already selected vertical range line is the bug. these two UI elements are supposed to operated independently

### sessionInfo()

```R
> sessionInfo()
R version 4.3.1 (2023-06-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
 [1] tidyr_1.3.1                 teal.goshawk_0.1.15.9017    teal.modules.general_0.3.0  ggmosaic_0.3.3             
 [5] ggplot2_3.5.0               teal.modules.clinical_0.9.0 tern_0.9.3                  rtables_0.6.6              
 [9] formatters_0.5.5            teal.transform_0.5.0        teal.connectors.rice_0.2.0  teal_0.15.2                
[13] teal.slice_0.5.0            teal.data_0.5.0             teal.code_0.5.0             stringr_1.5.1              
[17] sparkline_2.0               ricepass_1.1.4              rice_3.0.1                  magrittr_2.0.3             
[21] goshawk_0.1.15.9013         dplyr_1.1.4                 googlesheets4_1.0.1         DescTools_0.99.54          
[25] shiny_1.8.1.1              

loaded via a namespace (and not attached):
  [1] rstudioapi_0.16.0     jsonlite_1.8.8        estimability_1.5      farver_2.1.1          rmarkdown_2.26        ragg_1.2.7           
  [7] geepack_1.3.10        fs_1.6.3              vctrs_0.6.5           memoise_2.0.1         askpass_1.2.0         htmltools_0.5.8.1    
 [13] forcats_1.0.0         curl_5.2.1            haven_2.5.4           broom_1.0.5           cellranger_1.1.0      sass_0.4.9           
 [19] bslib_0.7.0           htmlwidgets_1.6.4     fontawesome_0.5.2     emmeans_1.10.0        rootSolve_1.8.2.4     plotly_4.10.4        
 [25] cachem_1.0.8          mime_0.12             lifecycle_1.0.4       teal.widgets_0.4.2    pkgconfig_2.0.3       Matrix_1.6-1.1       
 [31] R6_2.5.1              fastmap_1.1.1         rbibutils_2.2.16      digest_0.6.35         Exact_3.2             ggnewscale_0.4.10    
 [37] colorspace_2.1-0      shinycssloaders_1.0.0 textshaping_0.3.7     crosstalk_1.2.1       labeling_0.4.3        fansi_1.0.6          
 [43] httr_1.4.7            compiler_4.3.1        gargle_1.2.1          proxy_0.4-27          withr_3.0.0           backports_1.4.1      
 [49] logger_0.3.0          MASS_7.3-60.0.1       openssl_2.1.1         gld_2.6.6             tools_4.3.1           robslopes_1.1.3      
 [55] googledrive_2.0.0     httpuv_1.6.15         shinyvalidate_0.1.3   glue_1.7.0            nlme_3.1-163          promises_1.2.1       
 [61] grid_4.3.1            rsconnect_1.2.2       checkmate_2.3.1       generics_0.1.3        gtable_0.3.4          tzdb_0.4.0           
 [67] class_7.3-22          data.table_1.15.4     lmom_3.0              hms_1.1.3             utf8_1.2.4            ggrepel_0.9.5        
 [73] pillar_1.9.0          later_1.3.2           splines_4.3.1         tern.gee_0.1.3        lattice_0.21-9        renv_1.0.3           
 [79] survival_3.5-7        tidyselect_1.2.1      knitr_1.45            teal.logger_0.2.0     xfun_0.43             expm_0.999-9         
 [85] DT_0.33               stringi_1.8.3         lazyeval_0.2.2        yaml_2.3.8            boot_1.3-29           shinyWidgets_0.8.4   
 [91] evaluate_0.23         tibble_3.2.1          cli_3.6.1             systemfonts_1.0.6     xtable_1.8-4          Rdpack_2.6           
 [97] munsell_0.5.1         jquerylib_0.1.4       Rcpp_1.0.12           teal.reporter_0.3.1   readxl_1.4.3          parallel_4.3.1       
[103] readr_2.1.5           assertthat_0.2.1      mcr_1.3.3             viridisLite_0.4.2     mvtnorm_1.2-4         scales_1.3.0         
[109] e1071_1.7-14          crayon_1.5.2          purrr_1.0.2           rlang_1.1.3           cowplot_1.1.3         shinyjs_2.1.0        
>
```

### Relevant log output

```R
no error is thrown. please see scereen shots above
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by gogonzo**
closes #230 

<details>
<summary>installation code</summary>

```r
remotes::install_github(
  "insightsengineering/goshawk", 
  ref = "230_display_vline@main"
)
```

</details>

<details>
<summary>Example graph</summary>

```r

pkgload::load_all("goshawk")
library(stringr)
library(tidyr)

# original ARM value = dose value
arm_mapping <- list(
  "A: Drug X" = "150mg QD",
  "B: Placebo" = "Placebo",
  "C: Combination" = "Combination"
)
color_manual <- c("150mg QD" = "#000000", "Placebo" = "#3498DB", "Combination" = "#E74C3C")
# assign LOQ flag symbols: circles for "N" and triangles for "Y", squares for "NA"
shape_manual <- c("N" = 1, "Y" = 2, "NA" = 0)

ADLB <- rADLB
var_labels <- lapply(ADLB, function(x) attributes(x)$label)
ADLB <- ADLB %>%
  mutate(AVISITCD = case_when(
    AVISIT == "SCREENING" ~ "SCR",
    AVISIT == "BASELINE" ~ "BL",
    grepl("WEEK", AVISIT) ~
      paste(
        "W",
        trimws(
          substr(
            AVISIT,
            start = 6,
            stop = str_locate(AVISIT, "DAY") - 1
          )
        )
      ),
    TRUE ~ NA_character_
  )) %>%
  mutate(AVISITCDN = case_when(
    AVISITCD == "SCR" ~ -2,
    AVISITCD == "BL" ~ 0,
    grepl("W", AVISITCD) ~ as.numeric(gsub("\\D+", "", AVISITCD)),
    TRUE ~ NA_real_
  )) %>%
  # use ARMCD values to order treatment in visualization legend
  mutate(TRTORD = ifelse(grepl("C", ARMCD), 1,
    ifelse(grepl("B", ARMCD), 2,
      ifelse(grepl("A", ARMCD), 3, NA)
    )
  )) %>%
  mutate(ARM = as.character(arm_mapping[match(ARM, names(arm_mapping))])) %>%
  mutate(ARM = factor(ARM) %>%
    reorder(TRTORD)) %>%
  mutate(
    ANRHI = case_when(
      PARAMCD == "ALT" ~ 60,
      PARAMCD == "CRP" ~ 11,
      PARAMCD == "IGA" ~ 80,
      TRUE ~ NA_real_
    ),
    ANRLO = case_when(
      PARAMCD == "ALT" ~ 20,
      PARAMCD == "CRP" ~ 7,
      PARAMCD == "IGA" ~ 40,
      TRUE ~ NA_real_
    )
  ) %>%
  rowwise() %>%
  group_by(PARAMCD) %>%
  mutate(LBSTRESC = ifelse(
    USUBJID %in% sample(USUBJID, 1, replace = TRUE),
    paste("<", round(runif(1, min = 25, max = 30))), LBSTRESC
  )) %>%
  mutate(LBSTRESC = ifelse(
    USUBJID %in% sample(USUBJID, 1, replace = TRUE),
    paste(">", round(runif(1, min = 70, max = 75))), LBSTRESC
  )) %>%
  ungroup()
attr(ADLB[["ARM"]], "label") <- var_labels[["ARM"]]
attr(ADLB[["ANRHI"]], "label") <- "Analysis Normal Range Upper Limit"
attr(ADLB[["ANRLO"]], "label") <- "Analysis Normal Range Lower Limit"

# add LLOQ and ULOQ variables
ADLB_LOQS <- goshawk:::h_identify_loq_values(ADLB, flag_var = "LOQFL")
ADLB <- left_join(ADLB, ADLB_LOQS, by = "PARAM")

# given the 2 param and 2 analysis vars we need to transform the data
plot_data_t1 <- ADLB %>%
  gather(
    ANLVARS, ANLVALS, PARAM, LBSTRESC, BASE2, BASE, AVAL, BASE, LOQFL,
    ANRHI, ANRLO, ULOQN, LLOQN
  ) %>%
  mutate(ANL.PARAM = ifelse(ANLVARS %in% c("PARAM", "LBSTRESC", "LOQFL"),
    paste0(ANLVARS, "_", PARAMCD),
    paste0(ANLVARS, ".", PARAMCD)
  )) %>%
  select(USUBJID, ARM, ARMCD, AVISITN, AVISITCD, ANL.PARAM, ANLVALS) %>%
  spread(ANL.PARAM, ANLVALS)

# the transformed analysis value variables are character and need to be converted to numeric for
# ggplot
# remove records where either of the analysis variables are NA since they will not appear on the
# plot and will ensure that LOQFL = NA level is removed
plot_data_t2 <- plot_data_t1 %>%
  filter(!is.na(BASE.CRP) & !is.na(AVAL.ALT)) %>%
  mutate_at(vars(contains(".")), as.numeric) %>%
  mutate(
    LOQFL_COMB = ifelse(LOQFL_CRP == "Y" | LOQFL_ALT == "Y", "Y", "N")
  )


g_correlationplot(
  label = "Correlation Plot",
  data = plot_data_t2,
  param_var = "PARAMCD",
  xaxis_param = c("CRP"),
  xaxis_var = "AVAL",
  xvar = "AVAL.CRP",
  yaxis_param = c("ALT"),
  yaxis_var = "BASE",
  yvar = "BASE.ALT",
  trt_group = "ARM",
  visit = "AVISITCD",
  visit_facet = TRUE,
  loq_legend = TRUE,
  unit = "AVALU",
  title_text = "Correlation of ALT to CRP",
  xaxis_lab = "CRP",
  yaxis_lab = "ALT",
  color_manual = color_manual,
  shape_manual = shape_manual,
  facet_ncol = 4,
  facet = FALSE,
  facet_var = "ARM",
  reg_line = FALSE,
  vline_vars = c("ANRHI.CRP", "ANRLO.CRP", "ULOQN.CRP", "LLOQN.CRP"),
  vline_vars_colors = c("yellow", "orange", "brown", "gold"),
  vline_vars_labels = c("ANRHI CRP Label", "ANRLO CRP Label", "ULOQN CRP Label", "LLOQN CRP Label"),
  rotate_xlab = FALSE,
  font_size = 14,
  dot_size = 2,
  reg_text_size = 3
)
```

</details>

| main | this |
|--------|-----|
| image |  image |

### CODE REVIEW

**Comment by npaszty** [comment]
the change looks very small.
not sure how to test this without establishing some infrastructure for testing like what we used to do:  docker, staged dependencies etc. which I don't have time to do. or is there an easy way to test this now?

**Comment by gogonzo** [comment]
> the change looks very small.
not sure how to test this without establishing some infrastructure for testing like what we used to do: docker, staged dependencies etc. which I don't have time to do. or is there an easy way to test this now?

Some way to install this is to:
- clone repo on your instance (ocean), 
- checkout branch,
- install from local, 
- then run the app

Or you can investigate example goshawk examples and confirm that issue on @main is addressed here.

Alternatively, we can review this within a team, merge it, deploy main to r-univers and then ask you to upgrade package from r-universe.

**Comment by npaszty** [comment]
@gogonzo 

thanks for the explanations. I like the last one "Alternatively, we can review this within a team, merge it, deploy main to r-univers and then ask you to upgrade package from r-universe."  😄

**Review by kartikeyakirar — APPROVED** [review]
LGTM: tested with code

**Comment by kartikeyakirar** [comment]
@npaszty bugs are fixed and it is available in[ r-universe](https://pharmaverse.r-universe.dev/goshawk) now.

**Comment by npaszty** [comment]
@kartikeyakirar 

the horizontal/vertical and LLOQN/ULOQN functionality seems to be working well now. thanks!

**Pull request merged**
